[package]
name = "android-intent"
version = "0.2.1"
edition = "2021"
repository = "https://github.com/rust-mobile/android-intent"
license = "MIT"
description = "Android intent utilities"

[dependencies]
jni = "0.21.1"
ndk-context = "0.1.1"

[workspace]
members = [
  "example"
]
